### ISSUE TITLE
Is the scope of this library to handle Backpressure?

### ISSUE THREAD

**Issue by sledorze** [chrismcleod/rx-eventstore-client#44]
The example would be: 
I'm an eventhandler and have a fast incoming stream of eventstore events but a slow read side database to write in and I do not want to die while processing that stream.

**Comment by chrismcleod** [comment]
There is an example in the examples file of using the incrementalRetry operator on the stream.  The idea is take any existing stream and add this operator to the end.  It will wait however many seconds to received the completion event, and if it does not, it will retry issuing the command.

https://github.com/chrismcleod/rx-eventstore-client/blob/master/src/example.ts#L46

**Comment by chrismcleod** [comment]
I misread your question.  Backpressure is NOT out of scope, I would love to accommodate that.  That comment above is still good info but as far as backpressure, I'm not sure what the mechanism would be on eventstore.  RxJS has throttle operators to slow down the processing of events, but the incoming events would not stop and so they would pile up in memory.  We would need some way to tell eventstore itself to slow down sending.  Do you know how the other clients handle this?

**Comment by sledorze** [comment]
ok @chrismcleod we're at it :)

The base principle of backpressure is a pull mechanism.
Each worker does its job (processing current events and pushing to the database) and ask for more events when done, that's the way it works under the hood.

So the worker should be able to 'pause' it's subscription from the eventStore until ready for more work.

I know it may feel fundamentally different from how rxjs is working hence my question about how do you plan to tackle this.

**Comment by sledorze** [comment]
you may look at https://monix.io/ for instance

**Comment by sledorze** [comment]
a lot of interesting material in there:
https://github.com/ReactiveX/rxjs/issues/71

Some people suggest to have a feedbackloop mechanism in order to prevent having to change the API as a whole..

**Comment by chrismcleod** [comment]
Ok so let's discuss this.  It seems EventStore has persistent subscriptions which can be configured to send a certain amount of events to a subscriber and wait until some configurable number of those events has been acked to send more.  So I'm thinking persistent subscriptions already have backpressure handled.

A client is already in charge of how many events to request from a simple Read Events Forward (Backward) and so that command also does not need backpressure.

That leaves us with SubscribeToStream where stream events will appear unbounded.  As far as I understand EventStore, there is no mechanism to tell a subscription to stop (pause) sending events.  Nor can you request any certain number of events.  Am I wrong?  If I am not wrong, then it seems our only choice is a lossy bounded buffer on the client side.

Do you have any thoughts on this or a proposal for how you would want backpressure to work?

**Comment by sledorze** [comment]
@chrismcleod thanks for clarifying on the eventstore side of things, I was focusing on the streaming part in the worker.
That means SubscribeToStream is dangerous and should be considered carefully.

We may read a little more..
http://doc.akka.io/docs/akka/2.5.4/scala/stream/stream-flows-and-basics.html#back-pressure-explained

**Comment by sledorze** [comment]
Two possibilities; a general solution that works backpressured by design.
On the other side; there's the other possibility to tackle backpressure as an afterthought.

I'm unsure about RxJs being a good solution for the first case (which I would favor) because at heart it has a push model.
I've not found any options yet in Js - hesitating to reinvent the wheel.
I know that maybe Monix will be ported to Js in the future.

As for the other possibility, I'm concerned and nervous about integrating it once all the business logic is written.

**Comment by chrismcleod** [comment]
A special BackpressuredSubscription could be implemented in this client which would subclass RxJS Subscriber and override the next method with a method that would perform a request(n).  request(n) could do a ReadStreamEventsForward with maxCount = n.  One problem with this is your slow stream, if it can never catch the head, would fall very far behind (unless you accept dropped events).

Another option worth investigating might be the node stream's pause method.

**Comment by chrismcleod** [comment]
It is definitely not a trivial problem and I would hope for help from contributors.  We may have to wait until we have more interest in this lib and more qualified developers than myself.

This library works using node TCP streams to read from the connection.  A root source observable is created from the data event of this stream.  Perhaps if we pause this stream, node can handle buffering incoming messages and rxjs is left alone.  Also, RxJS has several operators that could be used at the level of a completed message from eventstore.  For example, use the buffer operator to buffer all completed messages from eventstore and emit them using throttle.

I am happy to work with you and anyone else that comes along on a specific proposal for implementation.  I will be thinking about it in the mean time.

**Comment by sledorze** [comment]
@chrismcleod  Something to keep in mind; when you Buffer, you're already in trouble.

I understand your call about library contributors.
I have not enough time to invest into such projects and to be totally honnest with you, I don't think I would try to fix RxJs but start from adapted foundations and builds up the rest from there.

The best project to bet on may be that next Monix on Js stuff (yes the even-not-started project) as it will more be a port of a core that is already proven. :)

**Comment by chrismcleod** [comment]
Feel free to re-open if you have any ideas
